Объект, представляющий набор индексов, а также метод (способ), используемый для представления некоторой части последовательности, где
последовательность — контейнер, элементы которого представляют собой некую последовательность.

например тип str, tuple, list, numpy.array, pandas.Dataframe и т.д

In [1]:
a = [1,3,2,4,5,7,7,2,9,10]
str = 'Этот чудный день для среза!'


In [6]:
a[3:4]

[4]

In [61]:
a[-4::-2]

[7, 5, 2, 1]

### Формат
( START(опционально) : STOP(опционально) : STEP(опционально) )

##### где
START=None : Начальный индекс среза. Если не указан, используется индекс первого элемента «разрезаемого» объекта — `0`.

STOP : Конечный индекс. Если не указан, используется индекс последнего элемента «разрезаемого» объекта. Данный индекс не включается в выборку!!!

STEP=None : Шаг выборки. Отрицательное значение позволяет строить срез из элементов в обратном порядке. 

Параметр STEP(Шаг)
<table>
<tr>
<td>
знак "-"
</td>
<td>
двигаемся по индексам влево
</td>
</tr>
<tr>
<td>
без знака
</td>
<td>
двигаемся по индексам вправо
</td>
</tr>
</table>


In [111]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [112]:
# Доступ к опреденному элементу списка по индексу
a[9]

9

In [113]:
str

'Этот чудный день для среза!'

In [114]:
str[5]

'ч'

In [115]:
type(a[1])

int

In [27]:
a[5:6]

[5]

In [7]:
a[2:]

[2, 4, 5, 7, 7, 2, 9, 10]

In [72]:
type(a[-1:])

list

In [94]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [93]:
# Используем срез с параметром START
a[5:]

[5, 6, 7, 8, 9]

In [95]:
# Используем срез с параметром START и STOP
a[5:7]

[5, 6]

In [98]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
# Используем срез с параметром START и STOP со знаком "-"
a[10:]


[]

In [100]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
# Используем срез с параметром START и STOP со знаком "-"
a[1:-1]

[3, 2, 4, 5, 7, 7, 2, 9]

In [37]:
a[-8:5]

[2, 4, 5]

In [40]:
# Используем срез с параметром START и STOP и ШАГ
a[-9:9:2]

[3, 4, 7, 2]

In [11]:
# Используем срез с параметром START и ШАГ
a[9::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [43]:
# Используем срез только с параметром ШАГ
a[::3]

[1, 4, 7, 10]

In [47]:
a[10:0:-3]

[10, 7, 4]

In [50]:
# Используем срез только с параметром ШАГ, и применяем такое же действие к результату
a[::2][1:3]

[2, 5]

In [145]:
# Создадим двумерный массив
b = [a,a]
b

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [31]:
b[1][3:9:2]

[3, 5, 7]

In [169]:
c = [a,a[::-1],a[5:]+a[10:4:-1],a[1:6]+a[5:0:-1]]

In [148]:
c

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
 [5, 6, 7, 8, 9, 9, 8, 7, 6, 5],
 [1, 2, 3, 4, 5, 5, 4, 3, 2, 1]]

In [170]:
c[1,1]

TypeError: list indices must be integers or slices, not tuple

In [158]:
c[-100:][::-1]

[[1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
 [5, 6, 7, 8, 9, 9, 8, 7, 6, 5],
 [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [92]:
import numpy as np

In [165]:
c = np.array(c)

In [94]:
c

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
       [5, 6, 7, 8, 9, 9, 8, 7, 6, 5],
       [1, 2, 3, 4, 5, 5, 4, 3, 2, 1]])

In [135]:
c[800:-1000:-1]

array([[1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [5, 6, 7, 8, 9, 9, 8, 7, 6, 5],
       [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [122]:
c[0::,9:0:-4]

array([[9, 5, 1]])

In [134]:
c[1::-1,6:4:-1]

array([[3, 4],
       [6, 5]])

In [176]:
b_set = set([0,1,2,3])

In [179]:
b_set.add(4)

In [181]:
b_set

TypeError: 'set' object is not subscriptable

In [188]:
d_dict = dict({0: 0, 1:1})

In [192]:
d_dict[:]

TypeError: unhashable type: 'slice'

In [193]:
d_dict = dict({0: a, 1:1})

In [196]:
d_dict[0][5:1:-1]

[5, 4, 3, 2]

In [198]:
t_tuple = tuple([0,1,2,3,4])

In [202]:
t_tuple[::-1]

(4, 3, 2, 1, 0)

In [203]:
del a[3:5]

In [204]:
a

[0, 1, 2, 5, 6, 7, 8, 9]

In [205]:
del t_tuple[1:3]

TypeError: 'tuple' object does not support item deletion

In [206]:
d_dict[0]

[0, 1, 2, 5, 6, 7, 8, 9]

In [210]:
del d_dict[0][3:5]

In [211]:
d_dict

{0: [0, 1, 2, 9], 1: 1}