Объект, представляющий набор индексов, а также метод (способ), используемый для представления некоторой части последовательности, где
последовательность — контейнер, элементы которого представляют собой некую последовательность.

например тип str, tuple, list, numpy.array, pandas.Dataframe и т.д

In [80]:
a = [1,3,2,4,5,7,7,2,9,10]
str = 'Этот чудный день для среза!'


<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/initial_array.png" height = 100>

### Формат
( START(опционально) : STOP(опционально) : STEP(опционально) )

##### где
START=None : Начальный индекс среза. Если не указан, используется индекс первого элемента «разрезаемого» объекта — `0`.

STOP : Конечный индекс. Если не указан, используется индекс последнего элемента «разрезаемого» объекта. Данный индекс не включается в выборку!!!

STEP=None : Шаг выборки. Отрицательное значение позволяет строить срез из элементов в обратном порядке. 

Параметр STEP(Шаг)
<table>
<tr>
<td>
знак "-"
</td>
<td>
двигаемся по индексам влево
</td>
</tr>
<tr>
<td>
без знака
</td>
<td>
двигаемся по индексам вправо
</td>
</tr>
</table>


In [81]:
a

[1, 3, 2, 4, 5, 7, 7, 2, 9, 10]

#### Положительные индексы

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/initial_array.png" height = 100>

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/array_5_index_selected.png" height = 130>

In [82]:
# Доступ к опреденному элементу списка по индексу
a[5]

7

In [83]:
str

'Этот чудный день для среза!'

In [84]:
str[5]

'ч'

In [85]:
type(a[1])

int

#### Отрицательные индексы

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/-1.png" height = 100>

In [86]:
a[-1]

10


<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/2_all.png" height = 150>

In [87]:
# Используем срез с параметром START
a[2:]

[2, 4, 5, 7, 7, 2, 9, 10]

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/10_all.png" height = 150>

In [89]:
a[10:]

[]

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/3_4_slice.png" height = 150>

In [92]:
# Используем срез с параметром START и STOP
a[3:5]

[4, 5]

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/1_-1.png" height = 200>

In [93]:
# Используем срез с параметром START и STOP
a[1:-1]

[3, 2, 4, 5, 7, 7, 2, 9]

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/-6-4.png" height = 200>

In [96]:
a[4:6]

[5, 7]

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/-8_5.png" height = 200>

In [97]:
# Используем срез с параметром START и STOP
a[2:-5]

[2, 4, 5]

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/5_9_step_2.png" height = 200>

In [100]:
a[5:9:3]

[7, 9]

In [106]:
a[8:2:-1]

[9, 2, 7, 7, 5, 4]

In [107]:
a[-2:2:-1]

[9, 2, 7, 7, 5, 4]

In [29]:
a[-2:-8:-1]

[9, 2, 7, 7, 5, 4]

Еще раз повторим

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/-9_9_step2.png" height = 200>

In [108]:
a[-9:9:2]

[3, 4, 7, 2]

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/step-3.png" height = 200>

In [110]:
# Используем срез только с параметром ШАГ
a[::3]

[1, 4, 7, 10]

In [114]:
# Куда пропал четвертыйй элемент?
a[10:0:-3]

[10, 7, 4]

<img src="https://raw.githubusercontent.com/AndrewVolkova/Python/master/Visual/images/slices/2_step_slicing.png" height = 350>

In [117]:
# Используем срез только с параметром ШАГ,
# и применяем еще один срез к результату
a[::2][1:3][::-1]

[5, 2]

In [118]:
a

[1, 3, 2, 4, 5, 7, 7, 2, 9, 10]

In [119]:
a[::-1]

[10, 9, 2, 7, 7, 5, 4, 2, 3, 1]

In [120]:
str[::-1]

'!азерс ялд ьнед йындуч тотЭ'

In [121]:
# Создадим двумерный массив
b = [a,a]
b

[[1, 3, 2, 4, 5, 7, 7, 2, 9, 10], [1, 3, 2, 4, 5, 7, 7, 2, 9, 10]]

In [124]:
b[1][1:-1]

[3, 2, 4, 5, 7, 7, 2, 9]

In [31]:
b[1][3:9:2]

[3, 5, 7]

In [136]:
c = [a,a[::-1],a[5:]+a[10:4:-1],a[1:6]+a[5:0:-1]]

In [129]:
c[1:2]

[[10, 9, 2, 7, 7, 5, 4, 2, 3, 1]]

In [158]:
c[-100:][::-1]

[[1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
 [5, 6, 7, 8, 9, 9, 8, 7, 6, 5],
 [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [130]:
import numpy as np

In [155]:
c = np.array(c)

In [132]:
c

array([[ 1,  3,  2,  4,  5,  7,  7,  2,  9, 10],
       [10,  9,  2,  7,  7,  5,  4,  2,  3,  1],
       [ 7,  7,  2,  9, 10, 10,  9,  2,  7,  7],
       [ 3,  2,  4,  5,  7,  7,  5,  4,  2,  3]])

In [158]:
c[1::2,::-1]

array([[ 1,  3,  2,  4,  5,  7,  7,  2,  9, 10],
       [ 3,  2,  4,  5,  7,  7,  5,  4,  2,  3]])

In [134]:
c[1::-1,6:4:-1]

array([[3, 4],
       [6, 5]])

In [176]:
b_set = set([0,1,2,3])

In [179]:
b_set.add(4)

In [181]:
b_set

TypeError: 'set' object is not subscriptable

In [188]:
d_dict = dict({0: 0, 1:1})

In [192]:
d_dict[:]

TypeError: unhashable type: 'slice'

In [193]:
d_dict = dict({0: a, 1:1})

In [196]:
d_dict[0][5:1:-1]

[5, 4, 3, 2]

In [198]:
t_tuple = tuple([0,1,2,3,4])

In [202]:
t_tuple[::-1]

(4, 3, 2, 1, 0)

In [159]:
a

[1, 3, 2, 4, 5, 7, 7, 2, 9, 10]

In [160]:
del a[3:5]

In [161]:
a

[1, 3, 2, 7, 7, 2, 9, 10]

In [162]:
a

[1, 3, 2, 7, 7, 2, 9, 10]

In [163]:
b = a

In [164]:
del a[1:]

In [165]:
b

[1]

In [205]:
del t_tuple[1:3]

TypeError: 'tuple' object does not support item deletion

In [206]:
d_dict[0]

[0, 1, 2, 5, 6, 7, 8, 9]

In [210]:
del d_dict[0][3:5]

In [211]:
d_dict

{0: [0, 1, 2, 9], 1: 1}